services:
  backend:
    image: taskflow-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskFlowDb;User Id=sa;Password=YourStrong@Password;Encrypt=false;TrustServerCertificate=True;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER:-TaskFlow}
      - Jwt__ExpireDays=${JWT_EXPIRE_DAYS:-1}
      - TASKFLOW_ADMIN_PASSWORD=${TASKFLOW_ADMIN_PASSWORD}

  frontend:
    image: taskflow-frontend
    build:
      context: ../../projectsJavaScript/taskflow-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:4000/api
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskflow-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
